version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3.7.8-management
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.11
    environment: 
      - http.host=0.0.0.0
      - discovery.type=single-node
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - xpack.ml.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    environment:
      - XPACK_SECURITY_ENABLED=false
      - XPACK_GRAPH_ENABLED=false
      - XPACK_ML_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
      - XPACK_REPORTING_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch